version: "2.2"

volumes:
  stackerdb:
    driver: local

networks:
  backend:
    driver: bridge
    name: backend
    external: true

services:

  stacker:
    image: trydirect/stacker:0.0.5
    build: .
    container_name: stacker
    restart: always
    volumes:
      - ./stacker/files:/app/files
      - ./configuration.yaml:/app/configuration.yaml
      - ./migrations:/app/migrations
      - ./.env:/app/.env
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    environment:
      - RUST_LOG=debug
      - RUST_BACKTRACE=1
    depends_on:
      stackerdb:
        condition: service_healthy
    networks:
      - backend


  stackerdb:
    container_name: stackerdb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    image: postgres:16.0
    restart: always
    ports:
      - 5432
    env_file:
      - ./.env
    volumes:
      - stackerdb:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    networks:
      - backend
