version: "2.2"

volumes:
  stackerdb:
    driver: local

services:

  stacker:
    image: trydirect/stacker:0.0.3
    build: .
    container_name: stacker
    restart: always
    volumes:
      - ./stacker/files:/app/files
      - ./docker/configuration.yaml:/app/configuration.yaml
      - ./migrations:/app/migrations
      - ./docker/.env:/app/.env
    ports:
      - "8000:8000"
    env_file:
      - ./docker/.env
    environment:
      - RUST_LOG=debug
      - RUST_BACKTRACE=1
    depends_on:
      stackerdb:
        condition: service_healthy


  stackerdb:
    container_name: stackerdb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    image: postgres:16.0
    restart: always
    ports:
      - 5432:5432
    env_file:
      - ./docker/.env
    volumes:
      - stackerdb:/var/lib/postgresql/data
      - ./docker/postgresql.conf:/etc/postgresql/postgresql.conf